Develop djones errors
davecoulter/YSE_PZ pull request #202
Opened 2022-06-27 05:37 UTC by djones1040

fixed a bug in DECam uploads and added some slightly more descriptive error messages for when things fail

2022-07-21 20:07 UTC, djones1040 commented
just added checking for multiple running instances of the most computationally-intensive crons - note that we now require the tendo module.

2022-07-22 20:50 UTC, davecoulter requested changes
See my comment on `from tendo import singleton` in `QUB_data.py`

2022-07-22 20:50 UTC, davecoulter commented on YSE_App/data_ingest/QUB_data.py
> +from tendo import singleton
DJ -- did you add a new package to your local environment? I checked yse_virtual, and I don't see this dependency on prod. If this requires a new package, you'll also need to update the requirements.txt. Next week PM and I will be happy to help with that process.

2022-07-28 17:47 UTC, davecoulter approved these changes
Looks good!

2022-07-28 17:47 UTC, merged